---
abstract: 'flexible perl-based service manager'
author:
  - 'Vyacheslav Matyukhin <mmcleric@yandex-team.ru>'
build_requires:
  Cwd: 0
  File::Find: 0
  Test::Class: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300007, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ubic
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Config: 0
  Config::Tiny: 0
  Data::Dumper: 0
  Exporter: 0
  Fcntl: 0
  File::Basename: 0
  File::Path: 0
  Getopt::Long: 2.33
  HTTP::Server::Simple::CGI: 0
  IO::Handle: 0
  IO::Socket: 0
  IPC::Open3: 0
  JSON: 0
  List::MoreUtils: 0
  List::Util: 0
  POSIX: 0
  Params::Validate: 0
  Pod::Usage: 0
  Scalar::Util: 0
  Storable: 0
  Term::ANSIColor: 0
  Time::HiRes: 0
  Try::Tiny: 0
  overload: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/berekuk/Ubic/issues
  homepage: http://github.com/berekuk/Ubic/wiki
  repository: git://github.com/berekuk/Ubic.git
version: 1.37_01
